"use client";

import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/theme-provider";
import QueryProvider from "@/components/providers/query-provider";
import { Toaster } from "react-hot-toast";
import { SocketContextProvider } from "@/components/providers/SocketProvider";
import AuthProvider from "@/components/providers/AuthProvider";

const mainFont = localFont({
  src: "../fonts/segoe-ui-historic.ttf",
});

// export const metadata: Metadata = {
//   title: "Facebook",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={cn(
          mainFont.className,
          "overflow-x-hidden bg-bg-1 h-screen w-full 320:w-screen"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            {/* <AuthProvider> */}
            <SocketContextProvider>
              {children}
              <Toaster />
            </SocketContextProvider>
            {/* </AuthProvider> */}
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
